/* Generated By:JavaCC: Do not edit this line. excelParserConstants.java */
package Analizadores;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface excelParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tipo = 1;
  /** RegularExpression Id. */
  int texto = 3;
  /** RegularExpression Id. */
  int entero = 4;
  /** RegularExpression Id. */
  int decimal = 5;
  /** RegularExpression Id. */
  int rango = 6;
  /** RegularExpression Id. */
  int condicion = 7;
  /** RegularExpression Id. */
  int fecha = 8;
  /** RegularExpression Id. */
  int hora = 9;
  /** RegularExpression Id. */
  int fechahora = 10;
  /** RegularExpression Id. */
  int seleccionaUno = 11;
  /** RegularExpression Id. */
  int seleccionaMultiple = 12;
  /** RegularExpression Id. */
  int nota = 13;
  /** RegularExpression Id. */
  int fichero = 14;
  /** RegularExpression Id. */
  int calcular = 15;
  /** RegularExpression Id. */
  int iniciar = 16;
  /** RegularExpression Id. */
  int finalizar = 17;
  /** RegularExpression Id. */
  int id = 18;
  /** RegularExpression Id. */
  int digito = 19;
  /** RegularExpression Id. */
  int letra = 20;
  /** RegularExpression Id. */
  int coma = 21;
  /** RegularExpression Id. */
  int punto = 22;
  /** RegularExpression Id. */
  int agrupacion = 25;
  /** RegularExpression Id. */
  int ciclo = 26;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TIPO = 1;
  /** Lexical state. */
  int AGCI = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"tipo\"",
    "<token of kind 2>",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiple\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "<id>",
    "<digito>",
    "<letra>",
    "\",\"",
    "\".\"",
    "<token of kind 23>",
    "<token of kind 24>",
    "\"agrupacion\"",
    "\"ciclo\"",
    "\"\\\"\"",
  };

}
