/* Generated By:JavaCC: Do not edit this line. parserAparienciaConstants.java */
package Analizadores.Apariencia;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserAparienciaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int texto = 2;
  /** RegularExpression Id. */
  int cadena = 3;
  /** RegularExpression Id. */
  int entero = 4;
  /** RegularExpression Id. */
  int decimal = 5;
  /** RegularExpression Id. */
  int rango = 6;
  /** RegularExpression Id. */
  int condicion = 7;
  /** RegularExpression Id. */
  int fecha = 8;
  /** RegularExpression Id. */
  int hora = 9;
  /** RegularExpression Id. */
  int fechahora = 10;
  /** RegularExpression Id. */
  int seleccionaUno = 11;
  /** RegularExpression Id. */
  int seleccionaMultiple = 12;
  /** RegularExpression Id. */
  int nota = 13;
  /** RegularExpression Id. */
  int multimedia = 14;
  /** RegularExpression Id. */
  int calcular = 15;
  /** RegularExpression Id. */
  int iniciar = 16;
  /** RegularExpression Id. */
  int finalizar = 17;
  /** RegularExpression Id. */
  int agrupacion = 18;
  /** RegularExpression Id. */
  int ciclo = 19;
  /** RegularExpression Id. */
  int digito = 20;
  /** RegularExpression Id. */
  int estilo = 21;
  /** RegularExpression Id. */
  int letra = 22;
  /** RegularExpression Id. */
  int coma = 23;
  /** RegularExpression Id. */
  int punto = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"texto\"",
    "\"cadena\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiple\"",
    "\"nota\"",
    "\"multimedia\"",
    "\"calcular\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "\"agrupacion\"",
    "\"ciclo\"",
    "<digito>",
    "<estilo>",
    "<letra>",
    "\",\"",
    "\".\"",
    "<token of kind 25>",
  };

}
