/* Generated By:JavaCC: Do not edit this line. parserAparienciaConstants.java */
package Analizadores.Apariencia;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserAparienciaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int texto = 2;
  /** RegularExpression Id. */
  int entero = 3;
  /** RegularExpression Id. */
  int decimal = 4;
  /** RegularExpression Id. */
  int rango = 5;
  /** RegularExpression Id. */
  int condicion = 6;
  /** RegularExpression Id. */
  int fecha = 7;
  /** RegularExpression Id. */
  int hora = 8;
  /** RegularExpression Id. */
  int fechahora = 9;
  /** RegularExpression Id. */
  int seleccionaUno = 10;
  /** RegularExpression Id. */
  int seleccionaMultiple = 11;
  /** RegularExpression Id. */
  int nota = 12;
  /** RegularExpression Id. */
  int multimedia = 13;
  /** RegularExpression Id. */
  int calcular = 14;
  /** RegularExpression Id. */
  int iniciar = 15;
  /** RegularExpression Id. */
  int finalizar = 16;
  /** RegularExpression Id. */
  int agrupacion = 17;
  /** RegularExpression Id. */
  int ciclo = 18;
  /** RegularExpression Id. */
  int digito = 19;
  /** RegularExpression Id. */
  int estilo = 20;
  /** RegularExpression Id. */
  int letra = 21;
  /** RegularExpression Id. */
  int coma = 22;
  /** RegularExpression Id. */
  int punto = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<token of kind 1>",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiple\"",
    "\"nota\"",
    "\"multimedia\"",
    "\"calcular\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "\"agrupacion\"",
    "\"ciclo\"",
    "<digito>",
    "<estilo>",
    "<letra>",
    "\",\"",
    "\".\"",
    "<token of kind 24>",
  };

}
