/* Generated By:JavaCC: Do not edit this line. excelParserConstants.java */
package Analizadores.idPregunta;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface excelParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int tipo = 1;
  /** RegularExpression Id. */
  int idpregunta = 2;
  /** RegularExpression Id. */
  int texto = 4;
  /** RegularExpression Id. */
  int entero = 5;
  /** RegularExpression Id. */
  int decimal = 6;
  /** RegularExpression Id. */
  int rango = 7;
  /** RegularExpression Id. */
  int condicion = 8;
  /** RegularExpression Id. */
  int fecha = 9;
  /** RegularExpression Id. */
  int hora = 10;
  /** RegularExpression Id. */
  int fechahora = 11;
  /** RegularExpression Id. */
  int seleccionaUno = 12;
  /** RegularExpression Id. */
  int seleccionaMultiple = 13;
  /** RegularExpression Id. */
  int nota = 14;
  /** RegularExpression Id. */
  int fichero = 15;
  /** RegularExpression Id. */
  int calcular = 16;
  /** RegularExpression Id. */
  int iniciar = 17;
  /** RegularExpression Id. */
  int finalizar = 18;
  /** RegularExpression Id. */
  int id = 19;
  /** RegularExpression Id. */
  int digito = 20;
  /** RegularExpression Id. */
  int letra = 21;
  /** RegularExpression Id. */
  int coma = 22;
  /** RegularExpression Id. */
  int punto = 23;
  /** RegularExpression Id. */
  int agrupacion = 26;
  /** RegularExpression Id. */
  int ciclo = 27;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int TIPO = 1;
  /** Lexical state. */
  int IDPREGUNTA = 2;
  /** Lexical state. */
  int AGCI = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"tipo\"",
    "\"idpregunta\"",
    "<token of kind 3>",
    "\"texto\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"selecciona_uno\"",
    "\"selecciona_multiple\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"iniciar\"",
    "\"finalizar\"",
    "<id>",
    "<digito>",
    "<letra>",
    "\",\"",
    "\".\"",
    "<token of kind 24>",
    "<token of kind 25>",
    "\"agrupacion\"",
    "\"ciclo\"",
    "\"\\\"\"",
  };

}
