/* Generated By:JavaCC: Do not edit this line. parserSugerirConstants.java */
package Analizadores.Sugerir;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserSugerirConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int numeral = 2;
  /** RegularExpression Id. */
  int corchA = 3;
  /** RegularExpression Id. */
  int corchC = 4;
  /** RegularExpression Id. */
  int ID = 5;
  /** RegularExpression Id. */
  int Cadena = 6;
  /** RegularExpression Id. */
  int dospuntos = 7;
  /** RegularExpression Id. */
  int punto = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "<ID>",
    "<Cadena>",
    "\"..\"",
    "\".\"",
  };

}
