/* Generated By:JavaCC: Do not edit this line. parserRequeridoConstants.java */
package Analizadores.Requerido;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserRequeridoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int fechahora = 2;
  /** RegularExpression Id. */
  int fecha = 3;
  /** RegularExpression Id. */
  int hora = 4;
  /** RegularExpression Id. */
  int fechaA = 5;
  /** RegularExpression Id. */
  int horaA = 6;
  /** RegularExpression Id. */
  int numeral = 7;
  /** RegularExpression Id. */
  int llaveA = 8;
  /** RegularExpression Id. */
  int llaveC = 9;
  /** RegularExpression Id. */
  int varP = 10;
  /** RegularExpression Id. */
  int entero = 11;
  /** RegularExpression Id. */
  int doble = 12;
  /** RegularExpression Id. */
  int numero = 13;
  /** RegularExpression Id. */
  int verdadero = 14;
  /** RegularExpression Id. */
  int falso = 15;
  /** RegularExpression Id. */
  int desigual = 16;
  /** RegularExpression Id. */
  int mayorigualque = 17;
  /** RegularExpression Id. */
  int menorigualque = 18;
  /** RegularExpression Id. */
  int si = 19;
  /** RegularExpression Id. */
  int no = 20;
  /** RegularExpression Id. */
  int suma = 21;
  /** RegularExpression Id. */
  int potencia = 22;
  /** RegularExpression Id. */
  int menos = 23;
  /** RegularExpression Id. */
  int multi = 24;
  /** RegularExpression Id. */
  int div = 25;
  /** RegularExpression Id. */
  int mod = 26;
  /** RegularExpression Id. */
  int igual = 27;
  /** RegularExpression Id. */
  int mayorque = 28;
  /** RegularExpression Id. */
  int menorque = 29;
  /** RegularExpression Id. */
  int and = 30;
  /** RegularExpression Id. */
  int or = 31;
  /** RegularExpression Id. */
  int not = 32;
  /** RegularExpression Id. */
  int parA = 33;
  /** RegularExpression Id. */
  int parC = 34;
  /** RegularExpression Id. */
  int identificador = 35;
  /** RegularExpression Id. */
  int caracter = 36;
  /** RegularExpression Id. */
  int cadena = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "<fechahora>",
    "<fecha>",
    "<hora>",
    "<fechaA>",
    "<horaA>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "<varP>",
    "<entero>",
    "<doble>",
    "<numero>",
    "\"verdadero\"",
    "\"falso\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"si\"",
    "\"no\"",
    "\"+\"",
    "\"^\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "<identificador>",
    "<caracter>",
    "<cadena>",
  };

}
