/* Generated By:JavaCC: Do not edit this line. parserEtiquetaConstants.java */
package Analizadores.Etiqueta;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserEtiquetaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int dospuntos = 2;
  /** RegularExpression Id. */
  int numeral = 3;
  /** RegularExpression Id. */
  int corchA = 4;
  /** RegularExpression Id. */
  int corchC = 5;
  /** RegularExpression Id. */
  int ID = 6;
  /** RegularExpression Id. */
  int Cadena = 7;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "\"..\"",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "<ID>",
    "<Cadena>",
  };

}
