/* Generated By:JavaCC: Do not edit this line. parserRestringirConstants.java */
package Analizadores.Restringir;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserRestringirConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int fechahora = 2;
  /** RegularExpression Id. */
  int fecha = 3;
  /** RegularExpression Id. */
  int hora = 4;
  /** RegularExpression Id. */
  int fechaA = 5;
  /** RegularExpression Id. */
  int horaA = 6;
  /** RegularExpression Id. */
  int punto = 7;
  /** RegularExpression Id. */
  int coma = 8;
  /** RegularExpression Id. */
  int dospuntos = 9;
  /** RegularExpression Id. */
  int numeral = 10;
  /** RegularExpression Id. */
  int llaveA = 11;
  /** RegularExpression Id. */
  int llaveC = 12;
  /** RegularExpression Id. */
  int varP = 13;
  /** RegularExpression Id. */
  int entero = 14;
  /** RegularExpression Id. */
  int doble = 15;
  /** RegularExpression Id. */
  int caracter = 16;
  /** RegularExpression Id. */
  int cadena = 17;
  /** RegularExpression Id. */
  int numero = 18;
  /** RegularExpression Id. */
  int verdadero = 19;
  /** RegularExpression Id. */
  int falso = 20;
  /** RegularExpression Id. */
  int desigual = 21;
  /** RegularExpression Id. */
  int mayorigualque = 22;
  /** RegularExpression Id. */
  int menorigualque = 23;
  /** RegularExpression Id. */
  int si = 24;
  /** RegularExpression Id. */
  int no = 25;
  /** RegularExpression Id. */
  int suma = 26;
  /** RegularExpression Id. */
  int potencia = 27;
  /** RegularExpression Id. */
  int menos = 28;
  /** RegularExpression Id. */
  int multi = 29;
  /** RegularExpression Id. */
  int div = 30;
  /** RegularExpression Id. */
  int mod = 31;
  /** RegularExpression Id. */
  int igual = 32;
  /** RegularExpression Id. */
  int mayorque = 33;
  /** RegularExpression Id. */
  int menorque = 34;
  /** RegularExpression Id. */
  int and = 35;
  /** RegularExpression Id. */
  int or = 36;
  /** RegularExpression Id. */
  int not = 37;
  /** RegularExpression Id. */
  int parA = 38;
  /** RegularExpression Id. */
  int parC = 39;
  /** RegularExpression Id. */
  int opcion = 40;
  /** RegularExpression Id. */
  int identificador = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "<fechahora>",
    "<fecha>",
    "<hora>",
    "<fechaA>",
    "<horaA>",
    "\".\"",
    "\",\"",
    "\"..\"",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "<varP>",
    "<entero>",
    "<doble>",
    "<caracter>",
    "<cadena>",
    "<numero>",
    "\"verdadero\"",
    "\"falso\"",
    "\"!=\"",
    "\">=\"",
    "\"<=\"",
    "\"si\"",
    "\"no\"",
    "\"+\"",
    "\"^\"",
    "\"-\"",
    "\"*\"",
    "\"div\"",
    "\"mod\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"opcion\"",
    "<identificador>",
  };

}
