/* Generated By:JavaCC: Do not edit this line. parserConfiguracionConstants.java */
package Analizadores.Configuracion;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConfiguracionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int titulo_formulario = 2;
  /** RegularExpression Id. */
  int idform = 3;
  /** RegularExpression Id. */
  int estilo = 4;
  /** RegularExpression Id. */
  int importar = 5;
  /** RegularExpression Id. */
  int codigo_principal = 6;
  /** RegularExpression Id. */
  int codigo_global = 7;
  /** RegularExpression Id. */
  int pagina = 8;
  /** RegularExpression Id. */
  int archivo = 9;
  /** RegularExpression Id. */
  int todo = 10;
  /** RegularExpression Id. */
  int cuadricula = 11;
  /** RegularExpression Id. */
  int id = 12;
  /** RegularExpression Id. */
  int codigo = 13;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int ID = 1;
  /** Lexical state. */
  int CODE = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"importar\"",
    "\"codigo_principal\"",
    "\"codigo_global\"",
    "\"pagina\"",
    "<archivo>",
    "\"todo\"",
    "\"cuadricula\"",
    "<id>",
    "<codigo>",
  };

}
