/* Generated By:JavaCC: Do not edit this line. parserEtiquetaConstants.java */
package Analizadores.Calcular;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserEtiquetaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ESPACIO = 1;
  /** RegularExpression Id. */
  int numeral = 2;
  /** RegularExpression Id. */
  int corchA = 3;
  /** RegularExpression Id. */
  int corchC = 4;
  /** RegularExpression Id. */
  int punto = 5;
  /** RegularExpression Id. */
  int doblepunto = 6;
  /** RegularExpression Id. */
  int Cualquiera = 7;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int funcion_vacia = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<ESPACIO>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\"..\"",
    "<Cualquiera>",
    "<ID>",
    "<funcion_vacia>",
  };

}
